(function(l,k){var g={analytics:{VERSIONS:"3.3.15",GTIME:null,TYPE:1,SCRIPT_URI:["http://stadig.ifeng.com/page.js"],SCRIPT_OBJ:[],SWF_URI:"http://y3.ifengimg.com/ed787/0912/flashCookie.swf",PARAM:{ref:"",snapid:"",uid:"",sid:"",editor:"",hook:"",pagepara:"",uri:"",versions:"",browser:""},init:function(b){var a=g.analytics,c=location.hostname;-1===c.indexOf("ifeng.com")&&-1===c.indexOf("phoenixtv.com")&&(a.VERSIONS="x3.3.14");a.PARAM.uri=b?b:"";a.process()},getParam:function(b){var a=g.analytics,c=
[],d=a.PARAM.ref=encodeURIComponent(g.analytics.Tools.referrer()),e=a.PARAM.info=g.client.info.get()?encodeURIComponent(g.client.info.get()):"";b=a.PARAM.uid=b;var f=a.PARAM.sid=a.Cookie.get("sid")?encodeURIComponent(a.Cookie.get("sid")):"",m=a.PARAM.editor=null!==k.getElementById("editor_name")?encodeURIComponent(k.getElementById("editor_name").innerHTML):"",h=a.PARAM.versions=a.VERSIONS,p=(new Date).getTime(),q=a.PARAM.pagepara="function"===typeof l.getStaPara?encodeURIComponent(l.getStaPara()):
"",n=a.PARAM.ci="function"===typeof l.getChannelInfo?encodeURIComponent(l.getChannelInfo()):"";c.push("uri="+(a.PARAM.uri?a.PARAM.uri:""));c.push("ref="+(d?d:""));c.push("snapid="+(e?e:""));c.push("uid="+(b?b:""));c.push("sid="+(f?f:""));c.push("editor="+(m?m:""));c.push("timestamp="+p);c.push("versions="+h);"undefined"===typeof l.sta_collection_time?c.push("ztime="+(p/1-(new Date).getTime()/1)):c.push("ztime="+(p/1-l.sta_collection_time/1));q&&c.push("pt="+q);n&&c.push("ci="+n);return c.join("&")},
process:function(){var b=g.analytics,a=b.Tools.domain(),c=b.Flash.FLASH_ID="ifengSwf_"+(new Date).getTime(),d="";if(b.Flash.isSupportFlash()){var e=k.getElementById("sta_collection"),d="",d=g.analytics.SWF_URI;e||(e=k.createElement("div"),e.id="sta_collection",k.getElementById("sta_collection_new").parentNode.insertBefore(e,k.getElementById("sta_collection_new")));d=k.all?'<object id="'+c+'" name="'+c+'" width="1" height="1" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"><param name="allowScriptAccess" value="always" /><param name="movie" value="'+
d+'" /> </object>':'<embed id="'+c+'" name="'+c+'" width="1" height="1" src="'+d+'" type="application/x-shockwave-flash" allowScriptAccess="always"></embed>';b.Flash.FLASH_TIME=(new Date).getTime();b.GTIME=setTimeout(function(){b.TYPE=2;b.gCallback(b.TYPE)},3E3);e.innerHTML=d}else{var f=b.Cookie,d=e=c="";b.TYPE=0;f.isSupportCookie()?(f.get("userid")&&"undefined"!=f.get("userid")&&"false"!=f.get("userid")?b.TYPE+="3":(f.set("userid",b.Tools.uid(),a),b.TYPE+="2"),c="?"+b.getParam(""===f.get("userid")?
b.Tools.uid():f.get("userid"))):(b.TYPE+="0",c="?"+b.getParam(b.Tools.uid()));a="&support="+b.TYPE;if(1<b.SCRIPT_URI.length)for(f=0;f<b.SCRIPT_URI.length;f++)d=b.SCRIPT_URI[f]+c+a,e="script_"+(new Date).getTime()+"_"+f,b.SCRIPT_OBJ.push(e),b.Tools.append(b.Tools.script(d,e));else d=b.SCRIPT_URI[0]+c+a,e="script_"+(new Date).getTime()+"_0",b.SCRIPT_OBJ.push(e),b.Tools.append(b.Tools.script(d,e));b.PARAM.ref=encodeURIComponent(l.location.href.replace(/&/g,"|"))}},gCallback:function(b){var a=g.analytics,
c=a.Tools.domain(),d=a.Flash.FLASH_ID,e=a.Flash.get(d,"www.ifeng.com","uid");a.TYPE=b?b:1;clearTimeout(a.GTIME);l.analytics_sta_callback=function(){};"string"===typeof e&&"undefined"===e||!1===e?(a.TYPE=!1===e?3:a.TYPE,a.Cookie.isSupportCookie()?a.Cookie.get("userid")&&"undefined"!=a.Cookie.get("userid")&&"false"!=a.Cookie.get("userid")?(e=a.Cookie.get("userid"),a.TYPE+="3"):(e=a.Tools.uid(),a.Cookie.set("userid",e,c),a.TYPE+="2"):(e=a.Tools.uid(),a.TYPE+="0"),a.Flash.set(d,"www.ifeng.com","uid",
e)):(a.TYPE=1,e=a.Flash.get(d,"www.ifeng.com","uid"),a.Cookie.isSupportCookie()?a.Cookie.get("userid")&&"undefined"!=a.Cookie.get("userid")&&"false"!=a.Cookie.get("userid")?a.TYPE+="3":(a.Cookie.set("userid",e,c),a.TYPE+="2"):a.TYPE+="0");b="";e="?"+a.getParam(e);c="";d="&ftime="+((new Date).getTime()/1-a.Flash.FLASH_TIME/1)+"&support="+a.TYPE;if(1<a.SCRIPT_URI.length)for(var f=0;f<a.SCRIPT_URI.length;f++)b=a.SCRIPT_URI[f]+e+d,c="script_"+(new Date).getTime()+"_"+f,a.SCRIPT_OBJ.push(c),a.Tools.append(a.Tools.script(b,
c));else b=a.SCRIPT_URI[0]+e+d,c="script_"+(new Date).getTime()+"_0",a.SCRIPT_OBJ.push(c),a.Tools.append(a.Tools.script(b,c));a.PARAM.ref=encodeURIComponent(l.location.href.replace(/&/g,"|"))},hook:function(b,a){var c=g.analytics,d=[],e=null,f="",m=e="",h;for(h in c.PARAM)"hook"===h?d.push(h+"="+(new Date).getTime()):"uri"!==h&&"snapid"!==h&&("info"===h?d.push("snapid="+c.PARAM[h]):"pagepara"===h?"#"!==c.PARAM.pagepara&&d.push("pt="+c.PARAM[h]):d.push(h+"="+c.PARAM[h]));d.push("timestamp="+(new Date).getTime());
d.push("support="+c.TYPE);h=0;if(c.SCRIPT_OBJ){for(h=0;h<c.SCRIPT_OBJ.length;h++)f=c.SCRIPT_OBJ[h],e=k.getElementById(f),g.analytics.Tools.remove(e);c.SCRIPT_OBJ.length=0}if(1<c.SCRIPT_URI.length)for(m="?"+d.join("&")+(b?b:""),h=0;h<c.SCRIPT_URI.length;h++)e=c.SCRIPT_URI[h]+m,f="script_"+(new Date).getTime()+"_"+h,e=c.Tools.script(e,f),c.SCRIPT_OBJ.push(f),c.Tools.append(e);else m="?"+d.join("&")+(b?b:""),f="script_"+(new Date).getTime()+"_0",e=c.Tools.script(c.SCRIPT_URI[0]+m,f),c.SCRIPT_OBJ.push(f),
c.Tools.append(e);c.PARAM.ref=encodeURIComponent(l.location.href.replace(/&/g,"|"));"function"===typeof a&&a()}}};g.analytics.Tools={referrer:function(){return k.referrer.replace(/&/g,"|")},iframe:function(){var b="";if(self!==top)try{b=k.referrer.replace(/&/g,"|")}catch(a){b="undefined"}return b},domain:function(){var b=location.hostname,a=0,c=b.length;if(-1!==b.indexOf(".ifeng"))a=b.indexOf(".ifeng");else if(-1!==b.indexOf(".phoenixtv"))a=b.indexOf(".phoenixtv");else return".ifeng.com";return b.substring(a,
c)},append:function(b){setTimeout(function(){k.body?k.body.insertBefore(b,k.body.firstChild):setTimeout(arguments.callee,0)},1)},remove:function(b){setTimeout(function(){b.parentNode.removeChild(b)},1)},script:function(b,a){var c=k.createElement("script");c.id=a;c.src=b;return c},uid:function(){var b=(new Date).getTime(),a="",c="",a=(2147483648*Math.random()|0).toString(36),c=Math.round(1E4*Math.random());return b+"_"+a+c},hasPlugin:function(b){b=b.toLowerCase();for(var a=0;a<navigator.plugins.length;a++)if(-1<
navigator.plugins[a].name.toLowerCase().indexOf(b))return!0},hasIEPlugin:function(b){try{return new ActiveXObject(b),!0}catch(a){return!1}},removeBlanks:function(b){for(var a="",c=0;c<b.length;c++){var d=b.charAt(c);" "!==d&&(a+=d)}return a}};g.analytics.Cookie={IS_HAS_COOKIE:null,get:function(b){for(var a=g.analytics.Tools.removeBlanks(k.cookie).split(";"),c=0;c<a.length;c++){var d=a[c].split("=");if(1<d.length&&d[0]===b)return d[1]}return""},set:function(b,a,c){var d=new Date;d.setTime(d.getTime()+
31104E6);b=b+"="+a+"; path=/; domain="+c+"; expires="+d.toGMTString();l.document.cookie=b},remove:function(b,a){g.analytics.Flash.isSupportFlash()&&(k.cookie=b+"=; path=/; domain="+a+"; expires=Thu, 01-Jan-70 00:00:01 GMT");return!1},isSupportCookie:function(){var b=g.analytics.Cookie,a=b.IS_HAS_COOKIE;null===a&&l.navigator.cookieEnabled&&(a=b.IS_HAS_COOKIE=!0);return a}};g.analytics.Flash={FLASH_ID:null,FLASH_TIME:null,IS_HAS_FLASH:null,LOCAL_OBJECT:null,get:function(b,a,c){var d=g.analytics.Flash;
return d.isSupportFlash()&&d.isAvailable(b)&&"undefined"!==typeof d.LOCAL_OBJECT.ifengFlashCookieRead&&d.LOCAL_OBJECT.ifengFlashCookieRead(a,c)?d.LOCAL_OBJECT.ifengFlashCookieRead(a,c):!1},set:function(b,a,c,d){var e=g.analytics.Flash,f=!1;e.isSupportFlash()&&e.isAvailable(b)&&"undefined"!==typeof e.LOCAL_OBJECT.ifengFlashCookieRead&&(e.LOCAL_OBJECT.ifengFlashCookieSet(a,c,d),f=!0);return f},remove:function(b,a,c){var d=g.analytics.Flash,e=!1;d.isSupportFlash()&&d.isAvailable(b)&&(d.LOCAL_OBJECT.ifengFlashCookieDelete(a,
c),e=!0);return e},clear:function(b,a){var c=g.analytics.Flash,d=!1;c.isSupportFlash()&&c.isAvailable(b)&&(c.LOCAL_OBJECT.ifengFlashCookieClear(a),d=!0);return d},getFlashObj:function(b){if(l.document[b])return l.document[b];if(-1===navigator.appName.indexOf("Microsoft")){if(k.embeds&&k.embeds[b])return k.embeds[b]}else return k.getElementById(b)},isAvailable:function(b){var a=g.analytics.Flash;b=a.getFlashObj(b);var c=!0,c=b?!0:!1;a.LOCAL_OBJECT=c?b:null;return c},isSupportFlash:function(){var b=
g.analytics,a=b.Flash.IS_HAS_FLASH;null===a&&(a=(a=b.Tools.hasPlugin("Shockwave Flash"))?a:b.Tools.hasIEPlugin("ShockwaveFlash.ShockwaveFlash"));return a}};g.client={};g.client.info={get:function(){var b=g.client;return b.device.get()+","+b.system.get()+","+b.browser.get()+","+b.screen.get()}};g.client.screen={get:function(){var b="",a="";try{b=l.screen.width,a=l.screen.height}catch(c){}return b+"*"+a}};g.client.system={get:function(){var b,a,c;c="";var d="Win",e=navigator.userAgent;c=navigator.platform;
b=0===c.indexOf("Win");a=0===c.indexOf("Mac");c="X11"===c||0===c.indexOf("Linux");if(b){if(/Win(?:dows )?([^do]{2})\s?(\d+\.\d+)?/.test(e))if("NT"===RegExp.$1)switch(RegExp.$2){case "5.0":d="windows_2000";break;case "5.1":d="windows_XP";break;case "6.0":d="windows_Vista";break;case "6.1":d="windows_7";break;case "6.2":d="windows_8";break;default:d="windows_NT"}else d="9x"===RegExp.$1?"windows_ME":e.match(/(Windows Phone)\s+([\d.]+)/)?"WP_"+e.match(/(Windows Phone)\s+([\d.]+)/)[2]:"Ph"===RegExp.$1?
"WP":"windows_"+RegExp.$2;e.match(/(Android)\s+([\d.]+)/)&&(d="Android_"+e.match(/(Android)\s+([\d.]+)/)[2])}else a?d=e.match(/(iPad).*OS\s([\d_]+)/)||e.match(/(iPhone\sOS)\s([\d_]+)/)?"iOS":"Mac":c?d=e.match(/(Android)\s+([\d.]+)/)?"Android_"+e.match(/(Android)\s+([\d.]+)/)[2]:"Linux":e.match(/Windows Phone/)?d="WP":e.match(/(iPad).*OS\s([\d_]+)/)||e.match(/(iPhone\sOS)\s([\d_]+)/)?d="iOS_"+(e.match(/(iPad).*OS\s([\d_]+)/)?e.match(/(iPad).*OS\s([\d_]+)/)[2]:e.match(/(iPhone\sOS)\s([\d_]+)/)[2]):
e.match(/(Android)\s+([\d.]+)/)&&(d="Android_"+e.match(/(Android)\s+([\d.]+)/)[2]);return d}};g.client.device={get:function(){var b="PC",a=navigator.userAgent,c=a.match(/(iPad).*OS\s([\d_]+)/),d=a.match(/(iPhone\sOS)\s([\d_]+)/),e=a.match(/(Android)\s+([\d.]+)/),f=a.match(/(Windows Phone)\s+([\d.]+)/);c&&(b="iPad");d&&(b="iPhone");e&&(a.toLowerCase().match(/mobile/)?(a.match(/chrome\/([\d.]+)/)&&a.toLowerCase().match(/mobile/)||a.toLowerCase().match(/firefox\/([\d.]+)/)&&a.toLowerCase().match(/mobile/),
b="Phone"):b="Pad");f&&(b="Phone");return b}};g.client.browser={get:function(){var b=navigator.userAgent.toLowerCase(),a="",a=b.match(/(?:firefox|opera|safari|chrome|msie)[\/: ]([\d.]+)/)[1],c=/version.+safari/.test(b)||/safari[\/ ]+([\d.]+)/.test(b),d=/chrome\/([\d.]+)/.test(b)||/crios\/([\d.]+)/.test(b),e=/firefox/.test(b),f=/msie/.test(b),g=/opera/.test(b),h=/ucbrowser\/([\d.]+)/.test(b),k=/maxthon/.test(b),l=/lbbrowser/.test(b),n=/qqbrowser/.test(b),r=/se 2.+x/.test(b),a=a.split(".")[0];if(h)return a=
b.match(/ucbrowser\/([\d.]+)/)[1]?b.match(/ucbrowser\/([\d.]+)/)[1]:a,"UC_"+a;if(k)return a=b.match(/maxthon\/([\d.]+)/)[1]?b.match(/maxthon\/([\d.]+)/)[1]:a,"AU_"+a;if(l)return"LB_"+a;if(n)return a=b.match(/qqbrowser\/([\d.]+)/)[1]?b.match(/qqbrowser\/([\d.]+)/)[1]:a,"QQ_"+a;if(r)return"SG_"+a;if(e)return"FF_"+a;if(g)return"OP_"+a;if(d)return"CM_"+a;if(c)return b.match(/android/)?"WK_"+b.match(/webkit\/([\d.]+)/)[1]:"SF_"+a;if(f)return"IE_"+a}};l.analytics=g.analytics.init;l.hook=g.analytics.hook;
l.analytics_sta_callback=function(){g.analytics.gCallback()}})(window,document);window.analytics(encodeURIComponent(window.location.href));
